# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-29 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_queue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
